### ISSUE TITLE
我想在OPENWRT下使用可以吗

### ISSUE THREAD

**Issue by yiqungui** [linkease/ddnsto#114]
我想在OPENWRT下使用可以吗

**Comment by jannson** [comment]
DDNSTO 暂时不支持非我们开发的固件，等我们有精力了我们会支持。

需要开发一套分布式的系统，我们开发得差不多了，但是因为易有云 2.0 一直没发布，所以我们专攻易友先。

**Comment by waxly** [comment]
你好，请问ddnsto现在支持原生openwrt了吗，酷软支持的路由器好少，希望能把ddnsto支持到https://github.com/coolsnowwolf/lede这个项目中去。这样可以支持大家编译使用。

**Comment by jannson** [comment]
刚刚支持，代码位置：https://github.com/linkease/ddnsto-openwrt
一键安装脚本：https://firmware.koolshare.cn/binary/ddnsto/openwrt/
