### ISSUE TITLE
设备认证问题

### ISSUE THREAD

**Issue by Linqing0808** [linkease/ddnsto#123]
一台陌生设备获得认证后，多久时间才能取消那台设备的认证？因为有时候会用陌生电脑管理家里的设备，谢谢。

**Comment by Linqing0808** [comment]
刚才试了一下，发现不是认证设备的，是认证IP的，目前不知道多长时间会释放已经认证了的IP

**Comment by jannson** [comment]
没有时间限制，但是有数量的限制，也就是后面的会把前面的挤掉。

**Comment by Linqing0808** [comment]
> 沒有時間限制，但是有數量的限制，也就是後面的會把前面的擠掉。

希望增加时间限制和手动踢掉已认证的设备或IP

**Comment by jannson** [comment]
好的，我们易有云2.0 开发基本完成，我们准备回归 ddnsto 2.0 的开发。

**Comment by 333bbb** [comment]
此issue会被关闭，如果还有相关问题可以新开一个issue，感谢！
