### ISSUE TITLE
路由器ID问题

### ISSUE THREAD

**Issue by ka0596** [linkease/ddnsto#126]
几台设备绑定了同一个账户方便管理…
结果其中两台特别奇怪…
路由器ID无规律持续变化…
请问大神要怎么处理…

**Comment by jannson** [comment]
因为 mac 地址一样导致，我们下个版本来解决这个问题。

**Comment by 333bbb** [comment]
#125

**Comment by Alan-freeair** [comment]
> 因为 mac 地址一样导致，我们下个版本来解决这个问题。

两台都是老毛子固件（一台小米3G,一台K2P），ddnsto 版本3.0.0，依然出现ID相同的问题，和MAC地址没关系，和老毛子固件版本也没关系（我已经换了几个版本了），已经确认了两个wan口的MAC地址不一样。

完美解决办法：经过测试 ddnsto命令后加`-x 1`参数（默认是0），1可以换成1-99之间的任意数（我记得官方文档有说0-99）。即可生成新的ID，最有意思的是在的输入框中的Token 后面加`-x 1`即可，记得加空格。
![image](https://user-images.githubusercontent.com/85866086/191304814-a788683d-0feb-43ab-a58b-34a1959d6050.png)

亲测有效
