### ISSUE TITLE
路由器可以访问但是无法访问路由器上插着的U盘

### ISSUE THREAD

**Issue by DZ65367709** [linkease/ddnsto#128]
我的路由器通过ddnsto解析，目前能够正常访问，但是，插在路由器上的U盘却不能访问。
我在电脑上用Windows诊断，结果如下：

“文件和打印共享资源（我的解析域名）处于联机状态，检测到，但未对连接尝试做出响应。
远程计算机不接受端口445上的连接，这可能是由于防火墙或安全策略设置，或因为服务可能暂时不可用。Windows在计算机的防火墙上找不到任何问题。”

在ddnsto管理页面我是这样设置的：
前缀（省略），目标主机设置http：//192.168.8.1:21

我的网络是这样的：
联通光猫➡️主路由器（padavan）➡️旁路由（openwrt）科学上网
U盘接插主路由上，目的是希望能够远程访问。但是目前可以正常远程访问主路由器和旁路由，却无法利用上面的设置远程访问U盘。

请问怎样处理。谢了。

**Comment by 333bbb** [comment]
目前还不支持， 可以尝试使用我们的易有云产品，速度更快
