### ISSUE TITLE
DDNSTO无法访问主机上的虚拟机

### ISSUE THREAD

**Issue by hercules188** [linkease/ddnsto#131]
DDNSTO无法访问主机上的虚拟机

**Comment by DHDAXCW** [comment]
先确认虚拟机是https就输入ttps://*.*.*.*

**Comment by DHDAXCW** [comment]
先确认虚拟机是https就输入https://...

**Comment by jannson** [comment]
请截图看看虚拟机的网页信息，链接地址是什么样子的？
你内网的访问的浏览器链接

**Comment by 333bbb** [comment]
此issue会被关闭，如果你说的现象仍然存在，请附上截图等信息新开一个issue，感谢
