### ISSUE TITLE
小米ac2100路由器刷openwrt后安装ddnsto无法启动

### ISSUE THREAD

**Issue by jiale58** [linkease/ddnsto#135]
![8](https://user-images.githubusercontent.com/35733213/109690047-e3293d00-7bc0-11eb-80b0-9cf6d2c02d00.jpg)

**Comment by jiale58** [comment]
mips架构

**Comment by jiale58** [comment]
root@MiRouter:/# sh -c "$(curl -sSL http://firmware.koolshare.cn/binary/ddnsto/openwrt/install_ddnsto.sh)"
+ Download_Files http://firmware.koolshare.cn/binary/ddnsto/openwrt/ddnsto_mipsel.ipk /tmp/ddnsto_mipsel.ipk
+ local 'URL=http://firmware.koolshare.cn/binary/ddnsto/openwrt/ddnsto_mipsel.ipk'
+ local 'FileName=/tmp/ddnsto_mipsel.ipk'
+ command_exists curl
+ command -v curl
+ curl -sSLk http://firmware.koolshare.cn/binary/ddnsto/openwrt/ddnsto_mipsel.ipk -o /tmp/ddnsto_mipsel.ipk
+ Download_Files http://firmware.koolshare.cn/binary/ddnsto/openwrt/luci-app-ddnsto.ipk /tmp/luci-app-ddnsto.ipk
+ local 'URL=http://firmware.koolshare.cn/binary/ddnsto/openwrt/luci-app-ddnsto.ipk'
+ local 'FileName=/tmp/luci-app-ddnsto.ipk'
+ command_exists curl
+ command -v curl
+ curl -sSLk http://firmware.koolshare.cn/binary/ddnsto/openwrt/luci-app-ddnsto.ipk -o /tmp/luci-app-ddnsto.ipk
+ Download_Files http://firmware.koolshare.cn/binary/ddnsto/openwrt/luci-i18n-ddnsto-zh-cn.ipk /tmp/luci-i18n-ddnsto-zh-cn.ipk
+ local 'URL=http://firmware.koolshare.cn/binary/ddnsto/openwrt/luci-i18n-ddnsto-zh-cn.ipk'
+ local 'FileName=/tmp/luci-i18n-ddnsto-zh-cn.ipk'
+ command_exists curl
+ command -v curl
+ curl -sSLk http://firmware.koolshare.cn/binary/ddnsto/openwrt/luci-i18n-ddnsto-zh-cn.ipk -o /tmp/luci-i18n-ddnsto-zh-cn.ipk
+ opkg install /tmp/ddnsto_mipsel.ipk
Package ddnsto (0.3.0-1) installed in root is up to date.
+ opkg install /tmp/luci-app-ddnsto.ipk
Package luci-app-ddnsto (1.0.0-1) installed in root is up to date.
+ opkg install /tmp/luci-i18n-ddnsto-zh-cn.ipk
Package luci-i18n-ddnsto-zh-cn (1.0.0-1) installed in root is up to date.
  ____  ____  _   _ ____ _____ ___
  |  _ \|  _ \| \ | / ___|_   _/ _ \
  | | | | | | |  \| \___ \ | || | | |
  | |_| | |_| | |\  |___) || || |_| |
  |____/|____/|_| \_|____/ |_| \___/   ....is now installed!


  感谢使用 DDNSTO，请登录 https://www.ddnsto.com 获取 token 填入插件

**Comment by jannson** [comment]
手动运行下面命令试试：

/etc/init.d/ddnsto enable

**Comment by jiale58** [comment]
也没报错但还是显示未启动，奇怪阿
![223](https://user-images.githubusercontent.com/35733213/109827770-feef1a80-7c76-11eb-9d98-4ba388345a00.jpg)
![224](https://user-images.githubusercontent.com/35733213/109827784-01ea0b00-7c77-11eb-9d68-4a6bf4d4bea5.jpg)

**Comment by jiale58** [comment]
已解决，感谢

**Comment by jannson** [comment]
最后必须重启才能解决，因为 Openwrt 15 版本跟插件的开发方式不兼容导致。

**Comment by chalau** [comment]
> 手动运行下面命令试试：
> 
> /etc/init.d/ddnsto enable
> 
> 我定位发现好像是 Openwrt 的版本兼容性问题，有的版本需要手动运行这个命令了才可以

相同：
Newifi-D2 
架构 | MediaTek MT7621 ver:1 eco:3 x 4
固件版本 | OpenWrt Lite R22.2.2 @ chalau [2022/02/18] / LuCI Master (git-22.046.49039-d9baa31)
内核版本 | 5.4.175

运行：
/etc/init.d/ddnsto enable
reboot

服务启动成功，感谢！
