### ISSUE TITLE
请帮我！无法解析！谢谢

### ISSUE THREAD

**Issue by qiang310** [linkease/ddnsto#138]
http://r2sqiang.ddnsto.com:5000

**Comment by qiang310** [comment]
您请求的地址的连接已断开，出现这样的现场的原因可能有：
1. 在管理后台填的内网地址，在您的内网里本身已无法访问
2. 管理后台的 http 或 https 地址混用或填错
3. 您的设备连接未知原因已下线，请在管理后台确认您的设备是否还在线（有亮色并有连接速度显示表示还在线）
4. 若还无法解决你的问题，请到 DDNSTO Github 地址 反馈您的问题
5. 论坛问题反馈地址 KoolShare 论坛

以下情况可能会导致短暂的访问错误，请等待 10 秒 ~ 50 秒左右
* 刚添加或删除了新的子域名
* 您的设备在内网里的公网 ip 产生了变化

**Comment by jannson** [comment]
你的内网地址估计没填对。你要保证你的内网地址是填对的，且运行 DDNSTO 设备是可以连接上你内网的设备的。

**Comment by 333bbb** [comment]
此issue会被关闭，如果你说的现象仍然存在，请附上截图等信息新开一个issue，感谢
