### ISSUE TITLE
希望DDNSTO ，可以按戶收費方案，費用貴些沒關係！！

### ISSUE THREAD

**Issue by win28703** [linkease/ddnsto#139]
希望DDNSTO ，可以按戶收費方案！！
如何可以按戶收費，就連系我下，
看費用多少，均可接受！

連絡我：win28703@gmail.com

**Comment by jannson** [comment]
今天事情太多了，明天我来联系你。

**Comment by win28703** [comment]
那就等你消息，大致上以按戶收費，不以台數收費，訂三年，付費！！

**Comment by win28703** [comment]
麻煩下，有空時給我消息，謝謝！
