### ISSUE TITLE
您好，小宝大佬，DDNSTO现在是收费才能使用吗？

### ISSUE THREAD

**Issue by hellooldtimes** [linkease/ddnsto#140]
有没有限速版可以免费使用的？还是使用必须收费？

**Comment by jannson** [comment]
不收费不也可以用？
不收费也没限速，但是远程应用中心，收费版本才能用。

**Comment by hellooldtimes** [comment]
> 不收费不也可以用？
> 不收费也没限速，但是远程应用中心，收费版本才能用。

啊，看到了，感谢，非常好用。不过想问大佬一个问题，就是：群晖(地址192.168.1.11)里面装了docker，然后docker装了ddnsto和mongodb数据库，已经绑定了docker，然后添加域名映射的目标主机地址是数据库自己的地址(192.168.1.22)，这个地址是macvlan类型的(也就是虚拟成和群晖同一网络的地址)，网页那边的列表也显示出来了，但是就是连不上，不知道哪里问题？

**Comment by jannson** [comment]
谢谢，能自己发现问题。
