### ISSUE TITLE
总是提示连接断开

### ISSUE THREAD

**Issue by reviveymj** [linkease/ddnsto#141]
您请求的地址的连接已断开，出现这样的现场的原因可能有：
1. 在管理后台填的内网地址，在您的内网里本身已无法访问
2. 管理后台的 http 或 https 地址混用或填错
3. 您的设备连接未知原因已下线，请在管理后台确认您的设备是否还在线（有亮色并有连接速度显示表示还在线）
4. 若还无法解决你的问题，请到 DDNSTO Github 地址 反馈您的问题
5. 论坛问题反馈地址 KoolShare 论坛

以下情况可能会导致短暂的访问错误，请等待 10 秒 ~ 50 秒左右
* 刚添加或删除了新的子域名
* 您的设备在内网里的公网 ip 产生了变化
总是提示这个，删除从新添加也是这样。不知道什么问题，线路，http https 都反复试了。之前一直用的没有问题。

**Comment by reviveymj** [comment]
搞定了，软路由的时间不对了

**Comment by liumingIt331** [comment]
请问下怎么修复的，我的也有同样的问题，突然就连不上了

**Comment by reviveymj** [comment]
我的是openwrt，我这是因为系统时间不对了。把时间改对就可以了。

liumingIt331 ***@***.***> 于2021年3月25日周四 上午10:40写道：

**Comment by jannson** [comment]
谢谢，能自己发现问题。
时间不同步是一个坑，我们想办法在 DDNSTO 界面提示用户这个错误。谢谢~
