### ISSUE TITLE
老大，出现右侧只有设备id，其他信息无，打开后提示，请求的子域名不存在

### ISSUE THREAD

**Issue by donggua1118** [linkease/ddnsto#142]
老大 我是付费用户，这个问题已经出现2次了，上一次是在软路由处重新绑定了令牌，才解决，我都没有动软路由设置，为什么每次都出现这个问题

**Comment by jannson** [comment]
那肯定是自动掉线了。可以看看日志，看看是何原因掉线

**Comment by jannson** [comment]
还有确认路由器的时间是不是同步的，时间不对导致无法连接服务器

**Comment by 333bbb** [comment]
此issue会被关闭，如果你说的现象仍然存在，请附上截图等信息新开一个issue，感谢
