### ISSUE TITLE
docker内搭建的wordpress做内网穿透，但是访问不了

### ISSUE THREAD

**Issue by GongChangJL** [linkease/ddnsto#144]
我用docker搭建的wordpress。我本地访问wordpress也能访问到。
但是在咱们软件上面做了内网穿透，ip+端口号啥的都填对了，但就是访问不到

**Comment by 333bbb** [comment]
之前修复了一个php的问题可能已经解决你的现象，如果此问题还是存在，请附上更详细的截图或配置参数新建一个issue，谢谢
