### ISSUE TITLE
我是小白用户我使用openwrt软路由 为什么一直不能外网访问我的路由器 谢谢你

### ISSUE THREAD

**Issue by civizhou** [linkease/ddnsto#147]
我是小白用户我使用openwrt软路由 为什么一直不能外网访问我的路由器 谢谢你

**Comment by 333bbb** [comment]
请先根据官网的教程排查一下
https://www.ddnsto.com/zh/guide/koolshare_merlin.html#_3-openwrt%E5%9B%BA%E4%BB%B6

如果还是无法成功， 请把操作过程和遇到的错误一起发上来，方便我们帮你定位

**Comment by 333bbb** [comment]
此issue会被关闭，如果你说的现象仍然存在，请附上截图等信息新开一个issue，感谢
