### ISSUE TITLE
按照流程设置好之后一直连不上

### ISSUE THREAD

**Issue by deocean2021** [linkease/ddnsto#148]
一直显示连接错误。软路由内部显示ddns.to服务已经启动，在后台也能见到该设备，但就是连不上。只有第一台设备一直能连上，后面添加的都连不上。账号是付款账号，可以连接12台设备的。

**Comment by 333bbb** [comment]
可能是是那几台设备的mac地址相同

**Comment by 333bbb** [comment]
请截图或者提供更多配置详情给我们看一下
