### ISSUE TITLE
#各类问题/需求收集#

### ISSUE THREAD

**Issue by sadoneli** [linkease/ddnsto#59]
# 收集从论坛，公测群内收集到的一些反馈，建议
1. 【requset】QNAP arm架构 [CPU RTD1295](https://www.realtek.com/en/products/communications-network-ics/item/rtd1295)支持
2. 【question】iOS 支持tvOS不？
3. 【question】iOS公测邀请码怎么获取？
4. 【bug】windows客户端首次开启，点击微信按钮后二维码不能关闭，影响排版
5. 【requset】 同时共享多块硬盘（多个文件夹）功能（现在只能共享一个文件夹）
6. 【bug】设备重命名后无法进行第二次重命名（windows客户端）
7. 【requset】 iOS不支持外部播放器（因为外部播放器打开后p2p就失效了）
8. 【requset】Ds918+   版本6.2.2，群辉版本不支持：https://github.com/koolshare/synology-easyexplorer
9. 【requset】隐藏linux系统文件，“.”开头的文件，隐藏windows系统文件/文件夹如lost+found

**Comment by snowleopardw** [comment]
1.【requset】QNAP arm架构 [CPU RTD1295](https://www.realtek.com/en/products/communications-network-ics/item/rtd1295)支持

多多益善（虽然我是918+目前还是提示无法安装的bug）

2.【question】iOS 支持tvOS不？

这个可以有（还可以在做安卓手机的同时顺便做AndroidTV版的，最好支持原生Launcher图标显示）

3.【question】iOS公测邀请码怎么获取？

发起问卷，用户填写邮箱，后台统计并发送邀请邮件

4. 【bug】windows客户端首次开启，点击微信按钮后二维码不能关闭，影响排版

可否曲线救国，通过设置“按键精灵/鼠标点击精灵”来巧妙解决

5.【requset】 同时共享多块硬盘（多个文件夹）功能（现在只能共享一个文件夹）

可以有。LEDE方面，可视客户端性能决定，加个性能自动判别就更好了

6.【bug】设备重命名后无法进行第二次重命名

iOS客户端实测可以二次重命名，请问此bug是只出现在某平台客户端上吗，可否参照iOS重命名函数实现方法解决

【P.s.】借楼求拉进iOS易有云微信群，微信号wangrui1994，谢谢！

**Comment by jannson** [comment]
先回答部分问题：
1. windows 客户端会进行全面的重构，主要实现文件自动同步与历史版本的功能。现在除非有严重影响使用的功能，修复速度会比较慢。二维码属于不影响使用的。
2. qnap x86 版本上 qnap 应用市场后，看与 qnap 的合作，应该能加入 arm 版本的。
3. 多文件夹后期肯定会加，但是影响范围挺大的，先这一版本上线稳定使用之后来加。
4. iOS公测邀请码我得问问我们的 iOS 开发者，后面统一回复。感谢试用！

**Comment by jannson** [comment]
@snowleopardw @sadoneli 请发送一个内测微信群链接，请加入我们内测群，然后我单独提供你一个 arm 版本的 qnap 插件试用吧！

**Comment by snowleopardw** [comment]
@jannson 

昨天@sadoneli 大神邀请我进的群，已进群，谢谢@jannson 大佬！

@sadoneli 和我想了一个解决方案：
新注册一个微信号（小号），分享该小号的加好友二维码。大家加这个小号好友，然后用该小号发送邀请进群哈

![IMG_0439](https://user-images.githubusercontent.com/7870528/56940482-4ec39e80-6b41-11e9-9256-b94aaa66eb13.JPG)

**Comment by jannson** [comment]
@snowleopardw 为你点赞，我马上来加好友。

**Comment by jannson** [comment]
@snowleopardw 
解决：【requset】QNAP arm架构 CPU RTD1295支持
链接里面有好几个 arm 版本，不知道哪个对应着 CPU RTD1295
，你试试 https://firmware.koolshare.cn/binary/Easy-Explorer-QNAP/

**Comment by jannson** [comment]
本项目以后仅保留 ddnsto 的反馈问题。
