### ISSUE TITLE
EasyExplorer 限制设备登录

### ISSUE THREAD

**Issue by seanria** [linkease/ddnsto#66]
例如我使用别人的设备远程登陆了一次 EasyExplorer，之后再输入网址就直接进入文件管理页面了。那么在我可以拿到这台设备的前提下，我如何可以限制这台设备的登录呢？谢谢。

**Comment by jannson** [comment]
我去，你说的这个问题貌似很关键，没有登出的功能！！！
下一个版本我们加上~
