### ISSUE TITLE
EasyExplorer Command Version

### ISSUE THREAD

**Issue by Hemingway2003** [linkease/ddnsto#82]
EasyExplorer可以支持命令行的吗，否则我在远端还是会调用xorg打开浏览器，速度很慢
类似于BaiduDownload-BSD那种的，支持ls，mkdir，download等功能

**Comment by jannson** [comment]
因为时间关系暂时不支持，不过我尝试过集成到 rclone 是可以的。如果你是专业人员，用过 rclone 吧？

未来我可以集成到 rclone 上，从而你可以用它的命令行来访问 easyexplorer

**Comment by jannson** [comment]
易有云 2.0 支持 linux 版本的命令行。
