### ISSUE TITLE
双向同步问题，

### ISSUE THREAD

**Issue by X1angyuxu** [linkease/ddnsto#87]
设置文件夹 提示  routerId not in params

**Comment by X1angyuxu** [comment]
![image](https://user-images.githubusercontent.com/54902525/65825052-b32b8b00-e2a4-11e9-9b14-e66c149f0358.png)

**Comment by X1angyuxu** [comment]
目标端不支持sync2way

**Comment by jannson** [comment]
路由器暂时不支持。
